# Generated by Django 6.0.3 on 2026-03-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, to='signals.topic'),
        ),
    ]
